// <auto-generated />
namespace AthletesAccounting.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class d1a : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(d1a));
        
        string IMigrationMetadata.Id
        {
            get { return "201607280645392_d1a"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
